# xlmlab <xlmlab.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
""
]

[DOCUMENTATION]
ORG_NAME=""
ORG_URL=""
ORG_LOGO =""
ORG_OFFICIAL_EMAIL=""
ORG_SUPPORT_EMAIL=""
ORG_DESCRIPTION=""

[[CURRENCIES]]
code=""
name=""
issuer=""
desc=""
image=""
conditions=""
status="live"
display_decimals=7
is_asset_anchored=true
anchor_asset_type="CRYPTO"
fixed_number=100000000000
